### ISSUE TITLE
RNAppsFlyer.logEvent is not a function

### ISSUE THREAD

**Issue by aharon-vish** [AppsFlyerSDK/appsflyer-react-native-plugin#259]
Hey,
After upgrade from 5.2.0 to 6.2.30

and replace track event with logEvent
I'm getting RNAppsFlyer.logEvent is not a function

node_modules/react-native-appsflyer/index.js // line 30

function logEventCallback(eventName, eventValues, successC, errorC) {
    return RNAppsFlyer.logEvent(eventName, eventValues, successC, errorC);  // here logEvent is undefined
}

**Comment by amit-kremer93** [comment]
Hi @aharon-vish please try to remove the plugin completely and install it again. if you are getting this error again, please contact our support team: support@appsflyer.com

**Comment by Revolt9k** [comment]
Same problem, reinstalling plugin doesn't help. Any other suggestions?
